[[ncbi-blast]]
arch = "aarch64"
git-tree-sha1 = "6752b97927b8dd7f5f7fbd13faf307953920b8f3"
os = "macos"

    [[ncbi-blast.download]]
    sha256 = "a9c89ba2abe752e111031729162c57f03e2695168ff49de29b7bd123959a4678"
    url = "https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.17.0/ncbi-blast-2.17.0+-universal-macosx.tar.gz"
[[ncbi-blast]]
arch = "x86_64"
git-tree-sha1 = "6752b97927b8dd7f5f7fbd13faf307953920b8f3"
os = "macos"

    [[ncbi-blast.download]]
    sha256 = "a9c89ba2abe752e111031729162c57f03e2695168ff49de29b7bd123959a4678"
    url = "https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.17.0/ncbi-blast-2.17.0+-universal-macosx.tar.gz"
[[ncbi-blast]]
arch = "aarch64"
git-tree-sha1 = "88a4af21d0f7de36e8506c910e2fa0da7bfe1297"
libc = "glibc"
os = "linux"

    [[ncbi-blast.download]]
    sha256 = "cb9ac252a1ac8767d90b0bf0a38486f3cb94f71ef9b6b8d194ded19b30250daf"
    url = "https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.17.0/ncbi-blast-2.17.0+-aarch64-linux.tar.gz"
[[ncbi-blast]]
arch = "x86_64"
git-tree-sha1 = "ddb981abd5ebe85262b661cbe077b6905df9f1cd"
libc = "glibc"
os = "linux"

    [[ncbi-blast.download]]
    sha256 = "3888112d8207831aa47371d93583c601f058f88b5db22dc782438b039a3a411b"
    url = "https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.17.0/ncbi-blast-2.17.0+-x64-linux.tar.gz"
[[ncbi-blast]]
arch = "x86_64"
git-tree-sha1 = "05f00a7fd4deec22718fc79ef0c75de70fe9cfec"
os = "windows"

    [[ncbi-blast.download]]
    sha256 = "ccde8788641e8f4137536aaadedfeac2f3599dbbc6166e701b5d89d19fa79038"
    url = "https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.17.0/ncbi-blast-2.17.0+-x64-win64.tar.gz"
